root: '265478608'
bt_uin: '3899129921'
enable_webui_interaction: true
debug: true
github_proxy: null
check_ncatbot_update: true
skip_ncatbot_install_check: false
websocket_timeout: 15
napcat:
  ws_uri: ws://localhost:3001
  ws_token: 1212//.././1/.2/1.98898989***(*(/=0==0=0=0=0====9-080-80-0-ojoju9jojopjopj.1
  ws_listen_ip: localhost
  webui_uri: http://localhost:6099
  webui_token: qVkC0,Mqh+=X;4{}
  enable_webui: true
  check_napcat_update: false
  stop_napcat: false
  remote_mode: false
  report_self_message: false
  report_forward_message_detail: true
plugin:
  plugins_dir: plugins
  plugin_whitelist: []
  plugin_blacklist: []
  skip_plugin_load: true
